# Generated by Django 5.1.3 on 2024-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by_profiles', to='interactions.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='associated_profiles', to='interactions.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='profile_img.jpeg', upload_to='profile_images'),
        ),
    ]
